DROP TABLE IF EXISTS UserRole;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS UserAddress;
DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS State;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Department;
