INSERT INTO User (AccountName, FirstName, LastName, BirthDate, DepartmentId) VALUES ('maxmin13', 'Max', 'Minardi', '1977-10-16', (SELECT Id FROM Department WHERE name = "Production"));
INSERT INTO UserRole (UserId, RoleId) VALUES ((SELECT Id FROM User WHERE AccountName = 'maxmin13'), (SELECT Id FROM Role WHERE Name = 'Administrator'));
INSERT INTO UserRole (UserId, RoleId) VALUES ((SELECT Id FROM User WHERE AccountName = 'maxmin13'), (SELECT Id FROM Role WHERE Name = 'User'));
INSERT INTO UserRole (UserId, RoleId) VALUES ((SELECT Id FROM User WHERE AccountName = 'maxmin13'), (SELECT Id FROM Role WHERE Name = 'Worker'));
INSERT INTO UserAddress (UserId, AddressId) VALUE ((SELECT Id FROM User WHERE AccountName = 'maxmin13'),(SELECT Id FROM Address WHERE PostalCode = '30010'));
INSERT INTO UserAddress (UserId, AddressId) VALUE ((SELECT Id FROM User WHERE AccountName = 'maxmin13'),(SELECT Id FROM Address WHERE PostalCode = 'A65TF12'));
INSERT INTO User (AccountName, FirstName, LastName, BirthDate, DepartmentId) VALUES ('artur', 'Arturo', 'Art', '1923-10-12', (SELECT Id FROM Department WHERE name = "Legal"));
INSERT INTO UserRole (UserId, RoleId) VALUES ((SELECT Id FROM User WHERE AccountName = 'artur'), (SELECT Id FROM Role WHERE Name = 'Administrator'));
INSERT INTO UserRole (UserId, RoleId) VALUES ((SELECT Id FROM User WHERE AccountName = 'artur'), (SELECT Id FROM Role WHERE Name = 'User'));
INSERT INTO UserAddress (UserId, AddressId) VALUE ((SELECT Id FROM User WHERE AccountName = 'artur'), (SELECT Id FROM Address WHERE PostalCode = 'A65TF12'));