---

tomcat_admin_user_name: "admin"
tomcat_admin_user_password: "secret"      
tomcat_group: "tomcat"
tomcat_user: "tomcat"
tomcat_admin_user: "admin"  
tomcat_keystore_password: "secret"  
mariadb_root_user_password: "mariadbrootsecret"   
mariadb_admin_user: "mariadbadmin" 
mariadb_admin_user_password: "mariadbadminsecret"  
...
